version: '3'
# services here:
services: 
  postgres:
    image: 'postgres:latest'
  redis: 
    image: 'redis:latest'
  api: 
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  alexandria: 
    build: 
      dockerfile: Dockerfile.dev
      context: ./alexandria
    volumes: 
      - /app/node_modules
      - ./alexandria:/app
  worker: 
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
  nginx:
    restart: always
    build: 
      # use custom configurations
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      # map to container port
      - '3050:80'